name: pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Set up pnpm and install
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Lint all files
        run: pnpm lint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 16.x
          - 18

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up pnpm and install
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Run tests
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Set up pnpm and install
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Build the project
        run: yarn build
      - name: Set up artifact
        uses: actions/upload-artifact@v2
        with:
          name: bundled-rbt
          path: |
            dist
